  Welcome to the Newspeak calculator.
  Reading Newspeak file 001.npk...
  Computing call graph...
  Type help for a list of commands.
$ unknown
  Unknown command 'unknown'. Try help.
$   Thank you for using the Newspeak calculator.
  Have a nice day...
