  Welcome to the Newspeak calculator.
  Reading Newspeak file 002.npk...
  Computing call graph...
  Type help for a list of commands.
$ where f
  f defined in file 002.c
$   Thank you for using the Newspeak calculator.
  Have a nice day...
