  Welcome to the Newspeak calculator.
  Reading Newspeak file 003.npk...
  Computing call graph...
  Type help for a list of commands.
$   Thank you for using the Newspeak calculator.
  Have a nice day...
