  Welcome to the Newspeak calculator.
  Reading Newspeak file 004.npk...
  Computing call graph...
  Type help for a list of commands.
$ call h
  main
    f
      h
    g
      f...
$   Thank you for using the Newspeak calculator.
  Have a nice day...
