  Welcome to the Newspeak calculator.
  Reading Newspeak file 006.npk...
  Computing call graph...
  Type help for a list of commands.
$ where f
  f not defined in any file.
$   Thank you for using the Newspeak calculator.
  Have a nice day...
