Debug: Parsing 156.c...
Debug: Parsing done.
Debug: Running first pass...
Debug: First pass done.
Debug: Translating 156.c...
Debug: Writing 156.no...
Debug: Writing done.
Debug: Linking files...
Debug: Importing 156.no...
Debug: Importing done.
Debug: Globals...
Debug: Functions...
Debug: Function linked: main
Debug: File linked.
Debug: Converting to Newspeak...
Debug: Conversion done.
Newspeak output
---------------
156.c
void main(void) {
  (156.c:27#1072)^int32 x;
  (156.c:28#1077)^0- =(int32) 3;
}


