Debug: Parsing 156.c...
Debug: Current size: 3
Debug: Parsing done.
Debug: Running goto elimination...
Debug: Goto elimination done.
Debug: Current size: 8
Debug: Typing...
Debug: 156.c:28#2: Running first pass...
Debug: First pass done.
Debug: Current size: 3
Debug: Translating...
Debug: Translation done.
Debug: Writing 156.no...
Debug: Writing done.
Debug: Linking files...
Debug: Importing 156.no...
Debug: Importing done.
Debug: Globals...
Debug: Functions...
Debug: Function linked: main
Debug: File linked.
Newspeak output
---------------
void (156.c:26#5)^main(void) {
  (156.c:27#6)^int32 x;
  (156.c:28#2)^x =(int32) 3;
}


