
Cil output for 658.c
--------------------
/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

#line 26 "658.c"
void main(void) 
{ 

  {
#line 27
  return;
}
}


Newspeak output
---------------
658.c
void main(void) {
}


