
Cil output for 659.c
--------------------
/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

#line 26 "659.c"
void main(void) 
{ int x ;

  {
#line 28
  return;
}
}


Newspeak output
---------------
659.c
void main(void) {
}


