
Cil output for 660.c
--------------------
/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

#line 26 "660.c"
void main(void) 
{ int x ;

  {
#line 28
  if (x) {
#line 28
    x ++;
  } else {
#line 28
    x --;
  }
#line 29
  return;
}
}


Newspeak output
---------------
660.c
void main(void) {
  (660.c:27#1053)^int32 x;
  (660.c:28#1058)^choose {
   -->
    (660.c:28#1058)^guard(! (x_int32 ==_int32 0));
    (660.c:28#1058)^x =(int32) coerce[-2147483648,2147483647] (x_int32 + 1);
   -->
    (660.c:28#1058)^guard((x_int32 ==_int32 0));
    (660.c:28#1058)^x =(int32) coerce[-2147483648,2147483647] (x_int32 - 1);
  }
}


