SRC=    ada2newspeak.ml ada_utils.mli print_syntax_ada.ml \
	ada_normalize.ml compiler.ml print_syntax_ada.mli \
	ada_normalize.mli compiler.mli syntax_ada.ml \
	ada_parse.ml firstpass.ml params.ml syntax_ada.mli \
	ada_parse.mli firstpass.mli params.mli \
	ada_utils.ml lexer.mll parser.mly

all: ../../bin/ada2newspeak	

../../bin/ada2newspeak : $(SRC)
	make -C ../..