# Project
DIR = newspeak
OBJ = ../newspeak/newspeak \
      npkstrip

# Documentation
DOC_DIR = doc

# Test
TGT = npkstrip

install: all
	cp $(TGT) ../../bin

include ../Makefile.common

include .depend
