# Project
DIR = newspeak
OBJ = ../version ../newspeak/newspeak \
	normalize store copy_propagation inline var_hoist npksimplify

# Executable
TGT = npksimplify

include ../Makefile.common

include .depend
